### PR TITLE
Show hostname in terminal title if session is over ssh

### PR DESCRIPTION
**Pull request by mafredri**
When logged in through ssh to a machine, say `mafredri@Denver`.
* No command active: `Denver: ~`
* Sleep 10: `Denver: mafredri: sleep 10`

### CODE REVIEW

**Comment by sindresorhus** [comment]
Maybe `Denver: mafredri:` => `mafredri@Denver:` for clarity and it kinda looks better?

**Comment by mafredri** [comment]
@sindresorhus really good suggestion, I like it. But it seems I kind of misunderstood what was already in the title. Since my example was so simple it didn't catch my error in thought :P. If you did `cd /home` the title would actually look like `Denver: home: sleep 10`.

I could also add the username, so `mafredri@Denver: home: sleep 10` (does it get a bit crowded, though?), then we would keep it in line with normal `pure` behavior by showing the path.

**Comment by sindresorhus** [comment]
Yeah, hostname is enough in the title.

**Comment by mafredri** [comment]
I did run it with a while locally as
* `Denver: /home`
* `(Denver) home: sleep 10`

I didn't like the inconsistency, of changing the hostname to parenthesis while a command was running. But maybe it could be `(Denver)` all the time, then we wouldn't get the double `:`.

**Comment by sindresorhus** [comment]
:+1:

**Comment by sindresorhus** [comment]
@mafredri Was thinking of doing another release. Anything else you want to fix / get in beforehand?

What's your npm username? Gonna add you.

**Comment by mafredri** [comment]
Can't think of anything major at this moment. Only thing I'd like to do something about is the excessive grayness when connected over ssh and inside a git repo:
 

But what to do about it I dunno yet :).

Didn't have an npm user beforehand, but created one now [mafredri](https://www.npmjs.com/~mafredri)

**Comment by sindresorhus** [comment]
> Only thing I'd like to do something about is the excessive grayness when connected over ssh and inside a git repo:

Agreed, but not a blocker. Can you open an issue?

> Didn't have an npm user beforehand, but created one now mafredri

Cool, added you. Feel free to do new future releases. Just use the following https://gist.github.com/sindresorhus/8435329 to make sure the release is properly pushed, and do a changelog thingy here: https://github.com/sindresorhus/pure/releases

**Comment by mafredri** [comment]
> Agreed, but not a blocker. Can you open an issue?

Done https://github.com/sindresorhus/pure/issues/126

> Cool, added you. Feel free to do new future releases. Just use the following [...]

Cheers :)! Sure, will do.

**Pull request closed without merging**
