### PR TITLE
Allow setting pre-prompt by user ENV var

### PR DESCRIPTION
**Pull request by samcv**
This will allow you to add stuff before the start of the prompt and/or
change the color of the path.

For example to change the color of the path the user can do:
PURE_PROMPT_PRE='%F{blue}'

To add a clock before the line and alter the color of the path:
PURE_PROMPT_PRE='%* %F{blue}'

Other things can be done but this gives the user a lot of control to
customize the prompt.

Let me know your thoughts, and if it makes more sense to split the
path color and the PRE into separate variables.

### CODE REVIEW

**Comment by sindresorhus** [comment]
The coloring is already being fixed in https://github.com/sindresorhus/pure/pull/472.

Are there any other use-cases for this?

**Comment by samcv** [comment]
@sindresorhus what I use this for is to add a clock at the left side of the prompt, as well as change the color of the directory.

So it would be nice if we could add additional things at the left hand side.

**Comment by ashb** [comment]
Something like the `pure_pieces` from https://github.com/intelfx/pure#custom-handlers would support this:

```zsh
# .zshrc

autoload -U promptinit; promptinit

# optionally define some options
PURE_CMD_MAX_EXEC_TIME=10

# optionally define custom generators
prompt_custom_time() {
	preprompt+=( "%F{gray}[%T]%f" )
}

prompt pure

# add the generator where it's needed
prompt_pure_pieces=(
	prompt_custom_time
	${prompt_pure_pieces:1}
)
```

@sindresorhus Would adding something like this be welcomed in a PR here?

**Comment by ashb** [comment]
See also #460

**Comment by sindresorhus** [comment]
Closing as this needs to be more fully thought through in #460. We also don't use environment variables anymore.

**Comment by sindresorhus** [comment]
@ashb Can you comment in that issue instead?

**Pull request closed without merging**
