### PR TITLE
Remove antigen and antibody from instruction

### PR DESCRIPTION
**Pull request by dobrovolsky**
Antigen tries to build from the "master" branch, but there isn't a branch with this name.

### CODE REVIEW

**Comment by mafredri** [comment]
Not sure wether or not we should change this here. I think this is worth reporting to the antigen project directly, it should be pulling the default branch otherwise this will become a profound issue for antigen users in the future. It could also be that it's failing because there is already a cached version of the project (with `master` branch), so it's pulling based on that. Not sure what the best solution would be to be honest.

**Comment by dobrovolsky** [comment]
Good point.
Seem like the Antigen project is "dead", so maybe it's better to remove it from readme at all?

**Comment by sindresorhus** [comment]
Yeah. Just remove it from the readme.

**Review by sindresorhus — APPROVED** [review]

**Comment by faizmokhtar** [comment]
@dobrovolsky @sindresorhus  Instead of removing can we update the instructions for antigen? I tried `pure` and I need to specify `--branch=main` for the installation to work. 

Something like this:
```
antigen bundle mafredri/zsh-async
antigen bundle sindresorhus/pure --branch=main
```

**Comment by sindresorhus** [comment]
We're not going to document inactive projects. There are enough other ZSH plugin managers.

**Pull request merged**
