### PR TITLE
Add pure10k to the list of ports

### PR DESCRIPTION
**Pull request by romkatv**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you include a screenshot in the Gist so people can see how it looks like?

**Comment by romkatv** [comment]
Done.

pure10k

**Comment by romkatv** [comment]
> This is not the Gist.

I've included a link to the screenshot in the gist and posted the same link here. If this isn't what you are asking for, could you clarify what I should do?

**Comment by sindresorhus** [comment]
I missed that. It was hidden in the comment. I meant; just add a readme.md file to the gist with the screenshot in it.

**Comment by romkatv** [comment]
Done.

Didn't know gist renders markdown. It looks much better with README.md indeed.

**Comment by romkatv** [comment]
Thanks for merging! And extra thanks for developing Pure. I've learned a lot from it.

**Pull request merged**
