### PR TITLE
Add `purer` fork to readme

### PR DESCRIPTION
**Pull request by DFurnes**
Hello! I made a [custom fork](https://github.com/dfurnes/purer) with few tiny modifications to Pure and wanted to share. All existing functionality should still work the same, but the prompt has been condensed to fit on a single line & I added a "vim-mode" color indicator.

I've published my fork to npm as [`purer-prompt`](https://www.npmjs.com/package/purer-prompt) and tested that it installs nicely alongside Pure. 😄

screen shot 2017-03-18 at 12 39 59 pm

### CODE REVIEW

**Comment by mikeerickson** [comment]
@dfurnes looks clean... did you remove the prompt character ( > )

**Comment by DFurnes** [comment]
@mikeerickson Yep! Didn't seem as necessary with everything on a single line.

**Comment by mikeerickson** [comment]
How does your prompt appear when previous command exited with error code?

**Comment by mikeerickson** [comment]
@Dfurnes sorry, forgot to tag you in previous message :)

**Comment by DFurnes** [comment]
@mikeerickson It'll show a little warning symbol at the end of the prompt. 

screen shot 2017-03-18 at 10 56 53 pm

**Pull request merged**
