### PR TITLE
Improve getting started for M1 mac users

### PR DESCRIPTION
**Pull request by teru01**
resolve
https://github.com/sindresorhus/pure/issues/584

reference
https://github.com/sindresorhus/pure/issues/584#issuecomment-989054653

### CODE REVIEW

**Comment by mafredri** [comment]
Hmm, this should not be required normally.

My guess is that for this to happen you may have installed Zsh via Homebrew (`/opt/homebrew/bin/zsh`), but are using the system (`/bin/zsh`) instead.

We should perhaps add a check during install instead.

**Comment by BeyondEvil** [comment]
I don't know what to tell you, dude.

I'm setting up a brand new M1 mac, I have not installed zsh via brew. I **did** however install pure using brew.

```sh
% ls -la /opt/hombrew/bin | grep zsh
%
% which zsh
/bin/zsh
% whence -p zsh
/bin/zsh
```

Before adding the `fpath+=...` the prompt did not load. Instead it printed `Usage` for the prompt command. 🤷‍♂️ 

I'm happy to provide more information and help troubleshoot if you want.

**Comment by mafredri** [comment]
@BeyondEvil the Homebrew installation method is not maintained by us, and it looks like it depends on zsh so it would've been pulled in when you installed it via Homebrew.

https://formulae.brew.sh/formula/pure#default

**Comment by MrCrunchwrap** [comment]
I am using the system `zsh` and I also had to add the line for pure to work

**Comment by likun7981** [comment]
I wrote a pure installation script for M1  https://github.com/likun7981/install-pure

**Comment by mafredri** [comment]
@likun7981 I hope you don't mind but I marked your comment off-topic since it is an install script for a **fork** of Pure.

**Comment by likun7981** [comment]
> @likun7981 I hope you don't mind but I marked your comment off-topic since it is an install script for a **fork** of Pure.

Ok I’m sorry, I delete it right now

**Pull request closed without merging**
